/* Delimitador cambiado a ; */
/* Conectando a localhost por MariaDB or MySQL (TCP/IP), usuario root, usando contraseña: No ... */
SELECT CONNECTION_ID();
SHOW VARIABLES;
/* Juego de caracteres: utf8mb4 */
SHOW /*!50002 GLOBAL */ STATUS;
SELECT NOW();
/* Conectado. ID de Hilo: 21 */
/* Reading function definitions from C:\Program Files\HeidiSQL\functions-mariadb.ini */
SHOW TABLES FROM `information_schema`;
SHOW DATABASES;
SHOW OPEN TABLES FROM prueba_techtalentheidi WHERE `in_use`!=0;
USE `prueba_techtalentheidi`;
/* Entrando a la sesión "Conex3" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='prueba_techtalentheidi';
SHOW TABLE STATUS FROM `prueba_techtalentheidi`;
SHOW FUNCTION STATUS WHERE `Db`='prueba_techtalentheidi';
SHOW PROCEDURE STATUS WHERE `Db`='prueba_techtalentheidi';
SHOW TRIGGERS FROM `prueba_techtalentheidi`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='prueba_techtalentheidi';
/* Cargando archivo "C:\Users\artha\OneDrive\Escritorio\java-bootcamp-techtalent-tgn2024\C3-Bases-Datos\UD14-DDL\create-database-biblio.sql" (25 B) en pestaña de consulta #1 */
/*  Escalando controles a DPI de pantalla: 150% */
/* Cargando archivo "C:\Users\artha\OneDrive\Escritorio\java-bootcamp-techtalent-tgn2024\C3-Bases-Datos\UD14-DDL\T14ej1meteo.sql" (36 B) en pestaña de consulta #2 */
USE `meteo`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='meteo';
SHOW TABLE STATUS FROM `meteo`;
SHOW FUNCTION STATUS WHERE `Db`='meteo';
SHOW PROCEDURE STATUS WHERE `Db`='meteo';
SHOW TRIGGERS FROM `meteo`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='meteo';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='meteo' AND TABLE_NAME='estacion' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `estacion` FROM `meteo`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='meteo'   AND TABLE_NAME='estacion'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='meteo'   AND TABLE_NAME='estacion'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW ENGINES;
SHOW COLLATION;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='meteo' AND TABLE_NAME='estacion';
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SHOW DATABASES;
/* Entrando a la sesión "Conex3" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='meteo';
SHOW TABLE STATUS FROM `meteo`;
SHOW FUNCTION STATUS WHERE `Db`='meteo';
SHOW PROCEDURE STATUS WHERE `Db`='meteo';
SHOW TRIGGERS FROM `meteo`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='meteo';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='meteo' AND TABLE_NAME='muestra' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `muestra` FROM `meteo`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='meteo'   AND TABLE_NAME='muestra'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='meteo'   AND TABLE_NAME='muestra'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='meteo' AND TABLE_NAME='muestra';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='meteo' AND TABLE_NAME='estacion' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `estacion` FROM `meteo`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='meteo'   AND TABLE_NAME='estacion'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='meteo'   AND TABLE_NAME='estacion'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='meteo' AND TABLE_NAME='estacion';
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` LIMIT 1000;
INSERT INTO `meteo`.`muestra` (`fecha`, `tempmin`, `tempmax`) VALUES ('2024-04-12', 5, 25);
/* Error de SQL (1452): Cannot add or update a child row: a foreign key constraint fails (`meteo`.`muestra`, CONSTRAINT `muestra_ibfk_1` FOREIGN KEY (`idestacion`) REFERENCES `estacion` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) */
SELECT `id`, LEFT(`lat`, 256) FROM `meteo`.`estacion` GROUP BY `id`, `lat` ORDER BY `lat` LIMIT 10000;
INSERT INTO `meteo`.`muestra` (`fecha`, `tempmin`, `tempmax`) VALUES ('2024-04-12', 5, 25);
/* Error de SQL (1452): Cannot add or update a child row: a foreign key constraint fails (`meteo`.`muestra`, CONSTRAINT `muestra_ibfk_1` FOREIGN KEY (`idestacion`) REFERENCES `estacion` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) */
INSERT INTO `meteo`.`muestra` (`fecha`, `tempmin`, `tempmax`) VALUES ('2024-04-12', 5, 25);
/* Error de SQL (1452): Cannot add or update a child row: a foreign key constraint fails (`meteo`.`muestra`, CONSTRAINT `muestra_ibfk_1` FOREIGN KEY (`idestacion`) REFERENCES `estacion` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) */
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
INSERT INTO `meteo`.`estacion` (`lat`, `longitud`) VALUES ('41', '2');
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=0;
UPDATE `meteo`.`estacion` SET `alt`=10 WHERE  `id`=0;
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=0;
UPDATE `meteo`.`estacion` SET `alt`=17 WHERE  `id`=0;
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=0;
UPDATE `meteo`.`estacion` SET `id`=1 WHERE  `id`=0;
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=1;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` LIMIT 1000;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SELECT `id`, LEFT(`lat`, 256) FROM `meteo`.`estacion` GROUP BY `id`, `lat` ORDER BY `lat` LIMIT 10000;
INSERT INTO `meteo`.`muestra` (`idestacion`) VALUES (1);
SELECT `idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax` FROM `meteo`.`muestra` WHERE  `idestacion`=1 AND `fecha`='' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
UPDATE `meteo`.`muestra` SET `fecha`='2024-04-12' WHERE  `idestacion`=1 AND `fecha`='0000-00-00' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
SELECT `idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax` FROM `meteo`.`muestra` WHERE  `idestacion`=1 AND `fecha`='2024-04-12' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
UPDATE `meteo`.`muestra` SET `tempmin`=8, `tempmax`=19, `precipita`=5, `hummin`=60, `hummax`=80, `velmin`=3, `velmax`=10 WHERE  `idestacion`=1 AND `fecha`='2024-04-12' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
SELECT `idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax` FROM `meteo`.`muestra` WHERE  `idestacion`=1 AND `fecha`='2024-04-12' AND `tempmin`=8 AND `tempmax`=19 AND `precipita`=5 AND `hummin`=60 AND `hummax`=80 AND `velmin`=3 AND `velmax`=10 LIMIT 1;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SELECT `id`, LEFT(`lat`, 256) FROM `meteo`.`estacion` GROUP BY `id`, `lat` ORDER BY `lat` LIMIT 10000;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
INSERT INTO `meteo`.`estacion` (`id`, `lat`, `longitud`, `alt`) VALUES (2, '40', '1.9', 200);
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=2;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SHOW CREATE TABLE `meteo`.`muestra`;
SHOW CREATE TABLE `meteo`.`estacion`;
SHOW CREATE TABLE `meteo`.`muestra`;
SHOW CREATE TABLE `meteo`.`estacion`;
SHOW CREATE TABLE `meteo`.`muestra`;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
INSERT INTO `meteo`.`estacion` (`id`, `lat`, `longitud`, `alt`) VALUES (3, '39', '1.5', 700);
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=3;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
USE `biblio`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='biblio';
SHOW TABLE STATUS FROM `biblio`;
SHOW FUNCTION STATUS WHERE `Db`='biblio';
SHOW PROCEDURE STATUS WHERE `Db`='biblio';
SHOW TRIGGERS FROM `biblio`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='biblio';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='tema' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `tema` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='tema'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='tema'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`tema`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='tema';
SELECT * FROM `biblio`.`tema` LIMIT 1000;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='socio' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `socio` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='socio'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='socio'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`socio`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='socio';
SELECT * FROM `biblio`.`socio` LIMIT 1000;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='editorial' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `editorial` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='editorial'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='editorial'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`editorial`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='editorial';
SELECT * FROM `biblio`.`editorial` LIMIT 1000;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='autor' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `autor` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='autor'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='autor'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`autor`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='autor';
SELECT * FROM `biblio`.`autor` LIMIT 1000;
SHOW DATABASES;
/* Entrando a la sesión "Conex3" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='biblio';
SHOW TABLE STATUS FROM `biblio`;
SHOW FUNCTION STATUS WHERE `Db`='biblio';
SHOW PROCEDURE STATUS WHERE `Db`='biblio';
SHOW TRIGGERS FROM `biblio`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='biblio';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='ejemplar' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `ejemplar` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='ejemplar'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='ejemplar'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`ejemplar`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='ejemplar';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='libro' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `libro` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='libro'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='libro'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`libro`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='libro';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='editorial' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `editorial` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='editorial'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='editorial'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`editorial`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='editorial';
SHOW CREATE TABLE `biblio`.`libro`;
SHOW CREATE TABLE `biblio`.`ejemplar`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='socio' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `socio` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='socio'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='socio'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`socio`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='socio';
ALTER TABLE `socio`
	CHANGE COLUMN `clavesocio` `clavesocio` INT NOT NULL DEFAULT 0 FIRST;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='biblio';
SHOW TABLE STATUS FROM `biblio`;
SHOW FUNCTION STATUS WHERE `Db`='biblio';
SHOW PROCEDURE STATUS WHERE `Db`='biblio';
SHOW TRIGGERS FROM `biblio`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='biblio';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='socio' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `socio` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='socio'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='socio'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`socio`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='socio';
/* Entrando a la sesión "Conex3" */
SHOW CREATE TABLE `biblio`.`socio`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='tema' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `tema` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='tema'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='tema'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`tema`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='tema';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='autor' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `autor` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='autor'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='autor'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`autor`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='autor';
ALTER TABLE `autor`
	CHANGE COLUMN `claveautor` `claveautor` INT NOT NULL DEFAULT 0 FIRST;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='biblio';
SHOW TABLE STATUS FROM `biblio`;
SHOW FUNCTION STATUS WHERE `Db`='biblio';
SHOW PROCEDURE STATUS WHERE `Db`='biblio';
SHOW TRIGGERS FROM `biblio`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='biblio';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='autor' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `autor` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='autor'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='autor'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`autor`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='autor';
/* Entrando a la sesión "Conex3" */
SHOW CREATE TABLE `biblio`.`autor`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='ejemplar' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `ejemplar` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='ejemplar'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='ejemplar'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`ejemplar`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='ejemplar';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='libro' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `libro` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='libro'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='libro'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`libro`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='libro';
SHOW CREATE TABLE `biblio`.`ejemplar`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='biblio' AND TABLE_NAME='editorial' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `editorial` FROM `biblio`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='biblio'   AND TABLE_NAME='editorial'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='biblio'   AND TABLE_NAME='editorial'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `biblio`.`editorial`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='biblio' AND TABLE_NAME='editorial';