SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
INSERT INTO `meteo`.`estacion` (`lat`, `longitud`) VALUES ('41', '2');
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=0;
UPDATE `meteo`.`estacion` SET `alt`=10 WHERE  `id`=0;
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=0;
UPDATE `meteo`.`estacion` SET `alt`=17 WHERE  `id`=0;
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=0;
UPDATE `meteo`.`estacion` SET `id`=1 WHERE  `id`=0;
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=1;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` LIMIT 1000;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SELECT `id`, LEFT(`lat`, 256) FROM `meteo`.`estacion` GROUP BY `id`, `lat` ORDER BY `lat` LIMIT 10000;
INSERT INTO `meteo`.`muestra` (`idestacion`) VALUES (1);
SELECT `idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax` FROM `meteo`.`muestra` WHERE  `idestacion`=1 AND `fecha`='' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
UPDATE `meteo`.`muestra` SET `fecha`='2024-04-12' WHERE  `idestacion`=1 AND `fecha`='0000-00-00' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
SELECT `idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax` FROM `meteo`.`muestra` WHERE  `idestacion`=1 AND `fecha`='2024-04-12' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
UPDATE `meteo`.`muestra` SET `tempmin`=8, `tempmax`=19, `precipita`=5, `hummin`=60, `hummax`=80, `velmin`=3, `velmax`=10 WHERE  `idestacion`=1 AND `fecha`='2024-04-12' AND `tempmin` IS NULL AND `tempmax` IS NULL AND `precipita` IS NULL AND `hummin` IS NULL AND `hummax` IS NULL AND `velmin` IS NULL AND `velmax` IS NULL LIMIT 1;
SELECT `idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax` FROM `meteo`.`muestra` WHERE  `idestacion`=1 AND `fecha`='2024-04-12' AND `tempmin`=8 AND `tempmax`=19 AND `precipita`=5 AND `hummin`=60 AND `hummax`=80 AND `velmin`=3 AND `velmax`=10 LIMIT 1;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
SHOW CREATE TABLE `meteo`.`muestra`;
SELECT * FROM `meteo`.`muestra` ORDER BY `idestacion` ASC LIMIT 1000;
SELECT `id`, LEFT(`lat`, 256) FROM `meteo`.`estacion` GROUP BY `id`, `lat` ORDER BY `lat` LIMIT 10000;
SHOW CREATE TABLE `meteo`.`estacion`;
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
INSERT INTO `meteo`.`estacion` (`id`, `lat`, `longitud`, `alt`) VALUES (2, '40', '1.9', 200);
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=2;
INSERT INTO `muestra` (`idestacion`, `fecha`, `tempmin`, `tempmax`, `precipita`, `hummin`, `hummax`, `velmin`, `velmax`) VALUES ('2', '2024-04-11', '5', '15', '2', '60', '80', '2', '8');
SELECT * FROM `meteo`.`estacion` LIMIT 1000;
INSERT INTO `meteo`.`estacion` (`id`, `lat`, `longitud`, `alt`) VALUES (3, '39', '1.5', 700);
SELECT `id`, `lat`, `longitud`, `alt` FROM `meteo`.`estacion` WHERE  `id`=3;